name: unit-test CI
run-name: Unit Test using Jest
on: [pull_request]
jobs:
  jest-expo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i jest --global
      - run: npm i jest-expo
      - run: jest
